"use strict";angular.module("com.2fdevs.videogular",["ngSanitize"]).run(["$templateCache",function($templateCache){$templateCache.put("vg-templates/vg-media-video","<video></video>");$templateCache.put("vg-templates/vg-media-audio","<audio></audio>");if(!Function.prototype.bind){Function.prototype.bind=function(oThis){if(typeof this!=='function'){throw new TypeError('Function.prototype.bind - what is trying to be bound is not callable');}
var aArgs=Array.prototype.slice.call(arguments,1),fToBind=this,fNOP=function(){},fBound=function(){return fToBind.apply(this instanceof fNOP?this:oThis,aArgs.concat(Array.prototype.slice.call(arguments)));};fNOP.prototype=this.prototype;fBound.prototype=new fNOP();return fBound;};}}]);"use strict";angular.module("com.2fdevs.videogular").constant("VG_STATES",{PLAY:"play",PAUSE:"pause",STOP:"stop"}).constant("VG_VOLUME_KEY","videogularVolume");"use strict";angular.module("com.2fdevs.videogular").controller("vgController",['$scope','$window','vgConfigLoader','vgFullscreen','VG_UTILS','VG_STATES','VG_VOLUME_KEY',function($scope,$window,vgConfigLoader,vgFullscreen,VG_UTILS,VG_STATES,VG_VOLUME_KEY){var currentTheme=null;var isFullScreenPressed=false;var isMetaDataLoaded=false;this.videogularElement=null;this.clearMedia=function(){this.mediaElement[0].src='';};this.onCanPlay=function(evt){this.isBuffering=false;$scope.$apply($scope.vgCanPlay({$event:evt}));};this.onVideoReady=function(){this.isReady=true;this.autoPlay=$scope.vgAutoPlay;this.playsInline=$scope.vgPlaysInline;this.cuePoints=$scope.vgCuePoints;this.currentState=VG_STATES.STOP;isMetaDataLoaded=true;if(VG_UTILS.supportsLocalStorage()){this.setVolume(parseFloat($window.localStorage.getItem(VG_VOLUME_KEY)||'1'));}
if($scope.vgConfig){vgConfigLoader.loadConfig($scope.vgConfig).then(this.onLoadConfig.bind(this));}
else{$scope.vgPlayerReady({$API:this});}};this.onLoadConfig=function(config){this.config=config;$scope.vgTheme=this.config.theme;$scope.vgAutoPlay=this.config.autoPlay;$scope.vgPlaysInline=this.config.playsInline;$scope.vgCuePoints=this.config.cuePoints;$scope.vgPlayerReady({$API:this});};this.onLoadMetaData=function(evt){this.isBuffering=false;this.onUpdateTime(evt);};this.onUpdateTime=function(event){this.currentTime=1000*event.target.currentTime;if(event.target.duration!=Infinity){this.totalTime=1000*event.target.duration;this.timeLeft=1000*(event.target.duration-event.target.currentTime);this.isLive=false;}
else{this.isLive=true;}
if(this.cuePoints){this.checkCuePoints(event.target.currentTime);}
$scope.vgUpdateTime({$currentTime:event.target.currentTime,$duration:event.target.duration});$scope.$apply();};this.checkCuePoints=function checkCuePoints(currentTime){for(var tl in this.cuePoints){for(var i=0,l=this.cuePoints[tl].length;i<l;i++){var cp=this.cuePoints[tl][i];if(!cp.timeLapse.end)cp.timeLapse.end=cp.timeLapse.start+1;if(currentTime<cp.timeLapse.end)cp.$$isCompleted=false;if(currentTime>cp.timeLapse.start){cp.$$isDirty=true;if(currentTime<cp.timeLapse.end){if(cp.onUpdate)cp.onUpdate(currentTime,cp.timeLapse,cp.params);}
if(currentTime>=cp.timeLapse.end){if(cp.onComplete&&!cp.$$isCompleted){cp.$$isCompleted=true;cp.onComplete(currentTime,cp.timeLapse,cp.params);}}}
else{if(cp.onLeave&&cp.$$isDirty){cp.onLeave(currentTime,cp.timeLapse,cp.params);}
cp.$$isDirty=false;}}}};this.onPlay=function(){this.setState(VG_STATES.PLAY);$scope.$apply();};this.onPause=function(){if(this.mediaElement[0].currentTime==0){this.setState(VG_STATES.STOP);}
else{this.setState(VG_STATES.PAUSE);}
$scope.$apply();};this.onVolumeChange=function(){this.volume=this.mediaElement[0].volume;$scope.$apply();};this.onPlaybackChange=function(){this.playback=this.mediaElement[0].playbackRate;$scope.$apply();};this.seekTime=function(value,byPercent){var second;if(byPercent){second=value*this.mediaElement[0].duration/100;this.mediaElement[0].currentTime=second;}
else{second=value;this.mediaElement[0].currentTime=second;}
this.currentTime=1000*second;};this.playPause=function(){if(this.mediaElement[0].paused){this.play();}
else{this.pause();}};this.setState=function(newState){if(newState&&newState!=this.currentState){$scope.vgUpdateState({$state:newState});this.currentState=newState;}
return this.currentState;};this.play=function(){this.mediaElement[0].play();this.setState(VG_STATES.PLAY);};this.pause=function(){this.mediaElement[0].pause();this.setState(VG_STATES.PAUSE);};this.stop=function(){this.mediaElement[0].pause();this.mediaElement[0].currentTime=0;this.currentTime=0;this.setState(VG_STATES.STOP);};this.toggleFullScreen=function(){if(!vgFullscreen.isAvailable||$scope.vgPlaysInline){if(this.isFullScreen){this.videogularElement.removeClass("fullscreen");this.videogularElement.css("z-index","auto");}
else{this.videogularElement.addClass("fullscreen");this.videogularElement.css("z-index",VG_UTILS.getZIndex());}
this.isFullScreen=!this.isFullScreen;}
else{if(this.isFullScreen){if(!VG_UTILS.isMobileDevice()){vgFullscreen.exit();}}
else{if(VG_UTILS.isMobileDevice()){if(VG_UTILS.isiOSDevice()){if(isMetaDataLoaded){this.enterElementInFullScreen(this.mediaElement[0]);}
else{isFullScreenPressed=true;this.play();}}
else{this.enterElementInFullScreen(this.mediaElement[0]);}}
else{this.enterElementInFullScreen(this.videogularElement[0]);}}}};this.enterElementInFullScreen=function(element){vgFullscreen.request(element);};this.changeSource=function(newValue){$scope.vgChangeSource({$source:newValue});};this.setVolume=function(newVolume){$scope.vgUpdateVolume({$volume:newVolume});this.mediaElement[0].volume=newVolume;this.volume=newVolume;if(VG_UTILS.supportsLocalStorage()){$window.localStorage.setItem(VG_VOLUME_KEY,newVolume.toString());}};this.setPlayback=function(newPlayback){$scope.vgUpdatePlayback({$playBack:newPlayback});this.mediaElement[0].playbackRate=newPlayback;this.playback=newPlayback;};this.updateTheme=function(value){var links=document.getElementsByTagName("link");var i;var l;if(currentTheme){for(i=0,l=links.length;i<l;i++){if(links[i].outerHTML.indexOf(currentTheme)>=0){links[i].parentNode.removeChild(links[i]);break;}}}
if(value){var headElem=angular.element(document).find("head");var exists=false;for(i=0,l=links.length;i<l;i++){exists=(links[i].outerHTML.indexOf(value)>=0);if(exists)break;}
if(!exists){headElem.append("<link rel='stylesheet' href='"+value+"'>");}
currentTheme=value;}};this.onStartBuffering=function(event){this.isBuffering=true;$scope.$apply();};this.onStartPlaying=function(event){this.isBuffering=false;$scope.$apply();};this.onComplete=function(event){$scope.vgComplete();this.setState(VG_STATES.STOP);this.isCompleted=true;$scope.$apply();};this.onVideoError=function(event){$scope.vgError({$event:event});};this.addListeners=function(){this.mediaElement[0].addEventListener("canplay",this.onCanPlay.bind(this),false);this.mediaElement[0].addEventListener("loadedmetadata",this.onLoadMetaData.bind(this),false);this.mediaElement[0].addEventListener("waiting",this.onStartBuffering.bind(this),false);this.mediaElement[0].addEventListener("ended",this.onComplete.bind(this),false);this.mediaElement[0].addEventListener("playing",this.onStartPlaying.bind(this),false);this.mediaElement[0].addEventListener("play",this.onPlay.bind(this),false);this.mediaElement[0].addEventListener("pause",this.onPause.bind(this),false);this.mediaElement[0].addEventListener("volumechange",this.onVolumeChange.bind(this),false);this.mediaElement[0].addEventListener("playbackchange",this.onPlaybackChange.bind(this),false);this.mediaElement[0].addEventListener("timeupdate",this.onUpdateTime.bind(this),false);this.mediaElement[0].addEventListener("error",this.onVideoError.bind(this),false);};this.init=function(){this.isReady=false;this.isCompleted=false;this.currentTime=0;this.totalTime=0;this.timeLeft=0;this.isLive=false;this.isFullScreen=false;this.isConfig=($scope.vgConfig!=undefined);if(vgFullscreen.isAvailable){this.isFullScreen=vgFullscreen.isFullScreen();}
this.updateTheme($scope.vgTheme);this.addBindings();if(vgFullscreen.isAvailable){document.addEventListener(vgFullscreen.onchange,this.onFullScreenChange.bind(this));}};this.onUpdateTheme=function onUpdateTheme(newValue){this.updateTheme(newValue);};this.onUpdateAutoPlay=function onUpdateAutoPlay(newValue){if(newValue)this.play(this);};this.addBindings=function(){$scope.$watch("vgTheme",this.onUpdateTheme.bind(this));$scope.$watch("vgAutoPlay",this.onUpdateAutoPlay.bind(this));$scope.$watch("vgPlaysInline",function(newValue,oldValue){this.playsInline=newValue;});$scope.$watch("vgCuePoints",function(newValue,oldValue){this.cuePoints=newValue;this.checkCuePoints(this.currentTime);}.bind(this));};this.onFullScreenChange=function(event){this.isFullScreen=vgFullscreen.isFullScreen();$scope.$apply();};$scope.$on('$destroy',this.clearMedia.bind(this));$scope.$on('$routeChangeStart',this.clearMedia.bind(this));this.init();}]);"use strict";angular.module("com.2fdevs.videogular").directive("vgLoop",[function(){return{restrict:"A",require:"^videogular",link:{pre:function(scope,elem,attr,API){var loop;scope.setLoop=function setLoop(value){if(value){API.mediaElement.attr("loop",value);}
else{API.mediaElement.removeAttr("loop");}};if(API.isConfig){scope.$watch(function(){return API.config;},function(){if(API.config){scope.setLoop(API.config.loop);}});}
else{scope.$watch(attr.vgLoop,function(newValue,oldValue){if((!loop||newValue!=oldValue)&&newValue){loop=newValue;scope.setLoop(loop);}
else{scope.setLoop();}});}}}}}]);"use strict";angular.module("com.2fdevs.videogular").directive("vgMedia",["$timeout","VG_UTILS","VG_STATES",function($timeout,VG_UTILS,VG_STATES){return{restrict:"E",require:"^videogular",templateUrl:function(elem,attrs){var vgType=attrs.vgType||"video";return attrs.vgTemplate||"vg-templates/vg-media-"+vgType;},scope:{vgSrc:"=?",vgType:"=?"},link:function(scope,elem,attrs,API){var sources;if(!attrs.vgType||attrs.vgType==="video"){attrs.vgType="video";}
else{attrs.vgType="audio";}
scope.onChangeSource=function onChangeSource(newValue,oldValue){if((!sources||newValue!=oldValue)&&newValue){sources=newValue;if(API.currentState!==VG_STATES.PLAY){API.currentState=VG_STATES.STOP;}
API.sources=sources;scope.changeSource();}};scope.changeSource=function changeSource(){var canPlay="";if(API.mediaElement[0].canPlayType){for(var i=0,l=sources.length;i<l;i++){canPlay=API.mediaElement[0].canPlayType(sources[i].type);if(canPlay=="maybe"||canPlay=="probably"){API.mediaElement.attr("src",sources[i].src);API.mediaElement.attr("type",sources[i].type);API.changeSource(sources[i]);break;}}}
else{API.mediaElement.attr("src",sources[0].src);API.mediaElement.attr("type",sources[0].type);API.changeSource(sources[0]);}
API.mediaElement[0].load();$timeout(function(){if(API.autoPlay&&!VG_UTILS.isMobileDevice()||API.currentState===VG_STATES.PLAY)API.play();});if(canPlay==""){API.onVideoError();}};API.mediaElement=elem.find(attrs.vgType);API.sources=scope.vgSrc;API.addListeners();API.onVideoReady();scope.$watch("vgSrc",scope.onChangeSource);if(API.isConfig){scope.$watch(function(){return API.config;},function(){if(API.config){scope.vgSrc=API.config.sources;}});}}}}]);"use strict";angular.module("com.2fdevs.videogular").directive("vgNativeControls",[function(){return{restrict:"A",require:"^videogular",link:{pre:function(scope,elem,attr,API){var controls;scope.setControls=function setControls(value){if(value){API.mediaElement.attr("controls",value);}
else{API.mediaElement.removeAttr("controls");}};if(API.isConfig){scope.$watch(function(){return API.config;},function(){if(API.config){scope.setControls(API.config.controls);}});}
else{scope.$watch(attr.vgNativeControls,function(newValue,oldValue){if((!controls||newValue!=oldValue)&&newValue){controls=newValue;scope.setControls(controls);}
else{scope.setControls();}});}}}}}]);"use strict";angular.module("com.2fdevs.videogular").directive("vgPreload",[function(){return{restrict:"A",require:"^videogular",link:{pre:function(scope,elem,attr,API){var preload;scope.setPreload=function setPreload(value){if(value){API.mediaElement.attr("preload",value);}
else{API.mediaElement.removeAttr("preload");}};if(API.isConfig){scope.$watch(function(){return API.config;},function(){if(API.config){scope.setPreload(API.config.preload);}});}
else{scope.$watch(attr.vgPreload,function(newValue,oldValue){if((!preload||newValue!=oldValue)&&newValue){preload=newValue;scope.setPreload(preload);}
else{scope.setPreload();}});}}}}}]);"use strict";angular.module("com.2fdevs.videogular").directive("vgTracks",[function(){return{restrict:"A",require:"^videogular",link:{pre:function(scope,elem,attr,API){var tracks;var trackText;var i;var l;scope.changeSource=function changeSource(){var oldTracks=API.mediaElement.children();for(i=0,l=oldTracks.length;i<l;i++){if(oldTracks[i].remove){oldTracks[i].remove();}}
if(tracks){for(i=0,l=tracks.length;i<l;i++){trackText="";trackText+='<track ';for(var prop in tracks[i]){trackText+=prop+'="'+tracks[i][prop]+'" ';}
trackText+='></track>';API.mediaElement.append(trackText);}}};scope.setTracks=function setTracks(value){tracks=value;API.tracks=value;scope.changeSource();};if(API.isConfig){scope.$watch(function(){return API.config;},function(){if(API.config){scope.setTracks(API.config.tracks);}});}
else{scope.$watch(attr.vgTracks,function(newValue,oldValue){if((!tracks||newValue!=oldValue)){scope.setTracks(newValue);}});}}}}}]);"use strict";angular.module("com.2fdevs.videogular").directive("videogular",[function(){return{restrict:"EA",scope:{vgTheme:"=?",vgAutoPlay:"=?",vgPlaysInline:"=?",vgCuePoints:"=?",vgConfig:"@",vgCanPlay:"&",vgComplete:"&",vgUpdateVolume:"&",vgUpdatePlayback:"&",vgUpdateTime:"&",vgUpdateState:"&",vgPlayerReady:"&",vgChangeSource:"&",vgError:"&"},controller:"vgController",controllerAs:"API",link:{pre:function(scope,elem,attr,controller){controller.videogularElement=angular.element(elem);}}}}]);"use strict";angular.module("com.2fdevs.videogular").service("vgConfigLoader",["$http","$q","$sce",function($http,$q,$sce){this.loadConfig=function loadConfig(url){var deferred=$q.defer();$http({method:'GET',url:url}).then(function success(response){var result=response.data;for(var i=0,l=result.sources.length;i<l;i++){result.sources[i].src=$sce.trustAsResourceUrl(result.sources[i].src);}
deferred.resolve(result);},function reject(){deferred.reject();});return deferred.promise;};}]);"use strict";angular.module("com.2fdevs.videogular").service("vgFullscreen",["VG_UTILS",function(VG_UTILS){var fsAPI;var polyfill=null;var APIs={w3:{enabled:"fullscreenEnabled",element:"fullscreenElement",request:"requestFullscreen",exit:"exitFullscreen",onchange:"fullscreenchange",onerror:"fullscreenerror"},newWebkit:{enabled:"webkitFullscreenEnabled",element:"webkitFullscreenElement",request:"webkitRequestFullscreen",exit:"webkitExitFullscreen",onchange:"webkitfullscreenchange",onerror:"webkitfullscreenerror"},oldWebkit:{enabled:"webkitIsFullScreen",element:"webkitCurrentFullScreenElement",request:"webkitRequestFullScreen",exit:"webkitCancelFullScreen",onchange:"webkitfullscreenchange",onerror:"webkitfullscreenerror"},moz:{enabled:"mozFullScreen",element:"mozFullScreenElement",request:"mozRequestFullScreen",exit:"mozCancelFullScreen",onchange:"mozfullscreenchange",onerror:"mozfullscreenerror"},ios:{enabled:"webkitFullscreenEnabled",element:"webkitFullscreenElement",request:"webkitEnterFullscreen",exit:"webkitExitFullscreen",onchange:"webkitfullscreenchange",onerror:"webkitfullscreenerror"},ms:{enabled:"msFullscreenEnabled",element:"msFullscreenElement",request:"msRequestFullscreen",exit:"msExitFullscreen",onchange:"MSFullscreenChange",onerror:"MSFullscreenError"}};for(var browser in APIs){if(APIs[browser].enabled in document){polyfill=APIs[browser];break;}}
if(VG_UTILS.isiOSDevice()){polyfill=APIs.ios;}
function isFullScreen(){return(document[polyfill.element]!=null);}
this.isAvailable=(polyfill!=null);if(polyfill){this.onchange=polyfill.onchange;this.onerror=polyfill.onerror;this.isFullScreen=isFullScreen;this.exit=function(){document[polyfill.exit]();};this.request=function(elem){elem[polyfill.request]();};}}]);"use strict";angular.module("com.2fdevs.videogular").service("VG_UTILS",["$window",function($window){this.fixEventOffset=function($event){var matchedFF=navigator.userAgent.match(/Firefox\/(\d+)/i)
if(matchedFF&&Number.parseInt(matchedFF.pop())<39){var style=$event.currentTarget.currentStyle||window.getComputedStyle($event.target,null);var borderLeftWidth=parseInt(style['borderLeftWidth'],10);var borderTopWidth=parseInt(style['borderTopWidth'],10);var rect=$event.currentTarget.getBoundingClientRect();var offsetX=$event.clientX-borderLeftWidth-rect.left;var offsetY=$event.clientY-borderTopWidth-rect.top;$event.offsetX=offsetX;$event.offsetY=offsetY;}
return $event;};this.getZIndex=function(){var zIndex=1;var tags=document.getElementsByTagName('*');for(var i=0,l=tags.length;i<l;i++){if(tags[i].style.zIndex&&parseInt(tags[i].style.zIndex)>zIndex){zIndex=parseInt(tags[i].style.zIndex)+1;}}
return zIndex;};this.isMobileDevice=function(){return(typeof window.orientation!=="undefined")||(navigator.userAgent.indexOf("IEMobile")!==-1);};this.isiOSDevice=function(){return(navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i));};this.supportsLocalStorage=function(){try{return'localStorage'in $window&&$window['localStorage']!==null;}catch(e){return false;}};}]);